feat/utils
lazoliver/guesser-game-api pull request #8
Opened 2024-01-15 14:50 UTC by lazoliver

Closes #2

2024-01-15 21:05 UTC, andref-dev requested changes
I'm having the following error when trying to run the project:
```
error: failed to run custom build command for `pear_codegen v0.1.5`

Caused by:
  process didn't exit successfully: `/Users/andresantos/Projects/guesser-game-api/target/debug/build/pear_codegen-fb2bd6f806307bf0/build-script-build` (exit status: 101)
  --- stderr
  Error: Pear requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.75.0 (2023-12-21)
  Minimum required:  1.31.0-nightly (2018-10-05)
  thread 'main' panicked at /Users/andresantos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pear_codegen-0.1.5/build.rs:24:13:
  Aborting compilation due to incompatible compiler.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```

I understand what it means, my question is if we want to rely our project on non stable rust versions, should we?
If not, is there a way to avoid having this requirement?

let me know your thoughts, and if we're going with the nightly requirement, let's make sure to add that to our README later on

2024-01-15 21:05 UTC, andref-dev commented on .vscode/settings.json
> +{
Let's add this folder (`.vscode`) to our gitignore. 

We can use this as reference:
https://stackoverflow.com/a/7927283

2024-01-15 21:05 UTC, andref-dev commented on src/handlers/utils.rs
> +    Json(health_response)
🔥

2024-01-16 14:29 UTC, lazoliver commented on .vscode/settings.json
> +{
Removed

2024-01-16 14:33 UTC, lazoliver commented
First of all, i'm sorry, you can solve this problem using following commands bellow:
```terminal
rustup toolchain install nightly
rustup default nightly
```

2024-01-16 17:50 UTC, andref-dev approved these changes
LGTM 🚀 

One suggestion based on your last comment, isntead of changing my whole environment to be nightly, I changed just this project  using:
```
cd guesser-game-api
rustup override set nightly
```

2024-01-17 11:55 UTC, merged